### ISSUE TITLE
Bug: SignUp is not working

### ISSUE THREAD

**Issue by sshsrn** [Anant7393/HackOctoberFest-2022#43]
![image](https://user-images.githubusercontent.com/62781914/197382813-cb4709e6-f993-46d5-9fc9-f3690638dc58.png)

Present behavior: Nothing happens on clicking **create an account**.
Expected behavior: Switch to signup div on clicking **create an account**.

**Comment by sshsrn** [comment]
@Anant7393 Kindly assign me this issue so that I can fix it.

**Comment by ankurdotexe** [comment]
@Anant7393  Please assign me this issue
